"""Fix transactions migration.

Revision ID: 176102e887d0
Revises: d6931189e442
Create Date: 2023-03-18 14:44:21.966721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '176102e887d0'
down_revision = 'd6931189e442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('market',
               existing_type=postgresql.ENUM('frac', 'normal', name='market_type'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('market',
               existing_type=postgresql.ENUM('frac', 'normal', name='market_type'),
               nullable=True)

    # ### end Alembic commands ###
